// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	endpoint "University-course-selection/http_cli/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeGetNameHandler(m, endpoints, options["GetName"])
	makePostHandler(m, endpoints, options["Post"])
	makeDeleteHandler(m, endpoints, options["Delete"])
	return m
}
