version: "3"

#services mysql redis  etcd
networks:
  byfn:

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root_test"
      - "MYSQL_DATABASE=user"
      - "TZ=Asia/Shanghai"
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"

  etcd1:
    container_name: etcd1
    image:  quay.io/coreos/etcd
    command: etcd -name etcd1 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - byfn


  etcd2:
    container_name: etcd2
    image:  quay.io/coreos/etcd
    command: etcd -name etcd2 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - "2381:2379"
      - "2382:2380"
    networks:
      - byfn

  etcd3:
    container_name: etcd3
    image:  quay.io/coreos/etcd
    command: etcd -name etcd3 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - "2383:2379"
      - "2384:2380"
    networks:
      - byfn
