// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "University-course-selection/http_cli/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GetNameEndpoint endpoint.Endpoint
	PostEndpoint    endpoint.Endpoint
	DeleteEndpoint  endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.HttpCliService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		DeleteEndpoint:  MakeDeleteEndpoint(s),
		GetNameEndpoint: MakeGetNameEndpoint(s),
		PostEndpoint:    MakePostEndpoint(s),
	}
	for _, m := range mdw["GetName"] {
		eps.GetNameEndpoint = m(eps.GetNameEndpoint)
	}
	for _, m := range mdw["Post"] {
		eps.PostEndpoint = m(eps.PostEndpoint)
	}
	for _, m := range mdw["Delete"] {
		eps.DeleteEndpoint = m(eps.DeleteEndpoint)
	}
	return eps
}
